### ISSUE TITLE
Adding embedding methods?

### ISSUE THREAD

**Issue by jisungyoon** [SciSciCollective/pyscisci#1]
Hi, I am Jisung from YY's group.
I'd like to contribute to this project regarding some network embedding methods that we have been implemented or invented. 

Maybe we can put the basic Node2vec, [SemAxis](https://arxiv.org/abs/1806.05521), or even method that we have been working for ScienceGenome project!

Let me know what you think! @ajgates42

**Comment by ajgates42** [comment]
Sure, that would be great.  The article titles are all easily accessible through the pub_df property of a database.  I haven't yet integrated abstracts from the MAG.  Is that enough for you to start?

**Comment by jisungyoon** [comment]
> Sure, that would be great. The article titles are all easily accessible through the pub_df property of a database. I haven't yet integrated abstracts from the MAG. Is that enough for you to start?

Yeah, Node2vec is just using the network information, so abstracts are not needed!

**Comment by ajgates42** [comment]
OK, I dont yet have a small test database setup, so the example to start with is likely APS---its small enough that development is possible.  The interface there is nearing stability, I'll review it tonight.  I think the Getting Started APS should work, but let me know if there's a problem.
Happy to video chat if that would be helpful for you to plan out your implementation.  

Thanks for your help!

**Comment by jisungyoon** [comment]
Hey @ajgates42 , do you have any plan for implementing a collaboration network or citation network?
If not, I can implement it also

**Comment by ajgates42** [comment]
Explicit functions for both networks are on the to-do list, but I haven't yet had a chance.
You're welcome to tackle either!  

I had planned for network specific functions to be in 'networks.py' and NLP specific functions to be in 'nlp.py'

**Comment by ajgates42** [comment]
> Hey @ajgates42 , do you have any plan for implementing a collaboration network or citation network?
> I need the network for embedding, and if not, I can implement it also.

I actually needed the co-authorship network for a project, so I went ahead and added a basic implementation.  Feel free to expand on it if you want temporal co-authorships or other functionality.

**Comment by jisungyoon** [comment]
Hey, I just checked your code, found some problems.
<img width="971" alt="Screen Shot 2020-06-15 at 2 04 09 PM" src="https://user-images.githubusercontent.com/10040328/84690829-23506e80-af11-11ea-87a1-0d18ae7097f2.png">
Maybe, numpy version problem?
Which version of NumPy are you using??

**Comment by ajgates42** [comment]
no, I just missed an enumerate when I transcribed over from a previous version.  Thanks for catching it!

**Comment by jisungyoon** [comment]
In my case, it works well with this code
`{aid:i for i, aid in enumerate(np.sort(mydblp.author2pub_df['AuthorId'].unique()))}
`
np.sort does not return the index.

**Comment by jisungyoon** [comment]
<img width="820" alt="Screen Shot 2020-06-15 at 2 28 14 PM" src="https://user-images.githubusercontent.com/10040328/84692830-7a0b7780-af14-11ea-9485-0bb7b5f55cc3.png">
Another error, I think coo_matrix is not subscriptable, so using csr-matrix?

**Comment by ajgates42** [comment]
OK, that's what I get for developing without checking on an example.  Thanks for your patience!
I've updated everything and included an example (Co-authorship network around Mark Newman in DBLP).  Definitely let me know if still gives some problems!

**Comment by jisungyoon** [comment]
Perfect!!

**Comment by jisungyoon** [comment]
Quick question! @ajgates42 

I am writing down the codes for embedding, but if we make it faster, I need a numba library.
Is it okay to include numba library to dependency?

**Comment by ajgates42** [comment]
For now, leave the numba import in a try except (for example, as in the nlp for sklearn)
If we decide its needed package wide (actually a great idea to speed up some of the metric applys) then we can move it to a required dependency.

**Comment by jisungyoon** [comment]
I am done with Node2vec and SemAxis, and try to make some examples.
I made a collaboration network with the focus_author with 'Albert-Laszlo Barabasi', 'Mark E. J. Newman'.
And made some 2D projection figures and SemAxis with two researchers.

Does it make sense to you? @ajgates42, you also included in this network:)
[Archive.zip](https://github.com/SciSciCollective/pyscisci/files/4784393/Archive.zip)

**Comment by jisungyoon** [comment]
'test.html' is 2-D projection of the embedding with UMAP, and 'semaxis.html' is the result of SemAxis:)

**Comment by ajgates42** [comment]
> I am done with Node2vec and SemAxis, and try to make some examples.
> I made a collaboration network with the focus_author with 'Albert-Laszlo Barabasi', 'Mark E. J. Newman'.
> And made some 2D projection figures and SemAxis with two researchers.
> 
> Does it make sense to you? @ajgates42, you also included in this network:)
> [Archive.zip](https://github.com/SciSciCollective/pyscisci/files/4784393/Archive.zip)

Cool!! I'm take a deep look later this week.  Thanks!

**Comment by jisungyoon** [comment]
Any comment?

**Comment by ajgates42** [comment]
Hi @jisungyoon,
I just took a look at the attached Archive, and all that I could find were the two figures.  Can you start a new branch with the code?  Without context for what I'm looking at, its a bit difficult to give any feedback.  The UMAP finds nice clusters of collaborators, but is there a reason SemAxis is only projected onto one dimension?  
Thanks!
Alex

**Comment by jisungyoon** [comment]
> Hi @jisungyoon,
> I just took a look at the attached Archive, and all that I could find were the two figures. Can you start a new branch with the code? 

Yeah, I made some codes on my forked repository, I will make a pull request.


> Without context for what I'm looking at, its a bit difficult to give any feedback. The UMAP finds nice clusters of collaborators, but is there a reason SemAxis is only projected onto one dimension?

The original purpose of the Semaxis is projecting the entities into some specific axis.
<img width="1700" alt="semaxis_diagram" src="https://user-images.githubusercontent.com/10040328/85433561-992c8980-b552-11ea-9b6c-0f9ca7ee41b1.png">
It usually used in word space, to characterize word semantics using many semantic axes.
In those examples, I define axis from two-person (Newman as a negative anchor and Barabasi as a positive anchor). Then, we can interpret persons with negative values as more Newman friendly people, and the person with positive values as more Barabasi friendly people.

Semaxis is quite useful when we find the relevant axis, it works for embedding with scientific mobility data in my ongoing proejct, also works on paper of YY.  https://arxiv.org/abs/2001.08199

**Comment by jisungyoon** [comment]
#2

**Comment by jisungyoon** [comment]
Forgot to close the issue
