### ISSUE TITLE
How to Import CSV Data

### ISSUE THREAD

**Issue by lilaclau** [SciSciCollective/pyscisci#21]
I have about 6000 citation relationship records (downloaded from web of science) that I have cleaned up in Excel. I'm trying to use the pyscisci package for co-citation analysis, but I'm not sure how to import my data in CSV format into pyscisci.

**Comment by ajgates42** [comment]
Hi @lilaclau, to use the full suit of pyscisci tools, you can set up a CustomDB by placing the citation information in one subfolder called 'pub2ref' and the publication metadata in another one called 'publication'.  Alternatively, you can apply just the co-citation method on your own dataframe (without creating a full database) where you need to change the cited and citing column names according to your own naming convention:
cocitation_network(pub2ref, focus_pub_ids=None, focus_constraint='citing', cited_col_name = 'CitedPublicationId', citing_col_name = 'CitingPublicationId', temporal=False, show_progress=False)

The full details are in the [network file](https://github.com/SciSciCollective/pyscisci/blob/master/pyscisci/network.py).
